# Generated by Django 5.0.6 on 2024-07-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('dishid', models.IntegerField(primary_key=True, serialize=False)),
                ('dishname', models.CharField(max_length=100)),
                ('imageurl', models.URLField()),
                ('ispublished', models.BooleanField(default=False)),
            ],
        ),
    ]
